services:
  db:
    build: .
    container_name: postgres-db
    environment:
      POSTGRES_USER: dhiya
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vector
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
