# Use a pre-built PostgreSQL image with pgvector
FROM ankane/pgvector

# Set environment variables
ENV POSTGRES_USER=dhiya
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=vector

# Expose the default PostgreSQL port
EXPOSE 5432
